# Generated by Django 4.2.6 on 2023-10-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('ItemName', models.CharField(blank=True, max_length=100, null=True)),
                ('ItemPrice', models.IntegerField(blank=True, null=True)),
                ('ItemImage', models.ImageField(blank=True, null=True, upload_to='ItemImages')),
                ('ItemDescription', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
